# Generated by Django 6.0.3 on 2026-03-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registration_time',
            new_name='created_at',
        ),
    ]
