# Generated by Django 6.0.3 on 2026-03-11 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_registration_time_registration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.hospital'),
        ),
    ]
